export const missingCountries = [
  { name: "Singapore", latLng: [1.3521, 103.8198] },
  { name: "BouvetIsland", latLng: [54.4208, 3.3464] },
  { name: "Bermuda", latLng: [32.3078, 64.7505] },
  { name: "Andorra", latLng: [42.5063, 1.5218] },
  { name: "AmericanSamoa", latLng: [14.271, 170.1322] },
  { name: "ÅlandIslands", latLng: [60.1785, 19.9156] },
]

export const countries = {
  IS: 10, // Iceland
  NO: 15, // Norway
  SE: 20, // Sweden
  NZ: 30, // New Zealand
  CA: 35, // Canada
  US: 40, // United States
  GB: 45, // United Kingdom
  DE: 50, // Germany
  FR: 55, // France
  JP: 60, // Japan
  AU: 70, // Australia
  CH: 75, // Switzerland
  NL: 80, // Netherlands
  BE: 85, // Belgium
  DK: 90, // Denmark
  FI: 95, // Finland
  AT: 100, // Austria
  IE: 105, // Ireland
  LU: 110, // Luxembourg
  SG: 115, // Singapore
  HK: 120, // Hong Kong
  KR: 125, // South Korea
  ES: 130, // Spain
  IT: 135, // Italy
  GR: 140, // Greece
  PT: 145, // Portugal
  CZ: 150, // Czech Republic
  EE: 155, // Estonia
  HU: 160, // Hungary
  LT: 165, // Lithuania
  PL: 170, // Poland
  SK: 175, // Slovakia
  SI: 180, // Slovenia
  LV: 185, // Latvia
  HR: 190, // Croatia
  CY: 195, // Cyprus
  MT: 200, // Malta
  AR: 205, // Argentina
  BR: 210, // Brazil
  CL: 215, // Chile
  MX: 220, // Mexico
  PE: 225, // Peru
  RU: 230, // Russia
  ZA: 235, // South Africa
  TR: 240, // Turkey
  CN: 245, // China
  IN: 250, // India
}

export const countryCodes = {
  IN: "India",
  US: "United States",
  CA: "Canada",
  GB: "United Kingdom",
  AU: "Australia",
  DE: "Germany",
  FR: "France",
  JP: "Japan",
  CN: "China",
  BR: "Brazil",
  RU: "Russia",
  ZA: "South Africa",
  MX: "Mexico",
  AR: "Argentina",
  ES: "Spain",
  IT: "Italy",
  NL: "Netherlands",
  SE: "Sweden",
  NO: "Norway",
  CH: "Switzerland",
  NZ: "New Zealand",
  SG: "Singapore",
  KR: "South Korea",
  ID: "Indonesia",
  MY: "Malaysia",
  TH: "Thailand",
  VN: "Vietnam",
  PH: "Philippines",
  EG: "Egypt",
  NG: "Nigeria",
  KE: "Kenya",
  GH: "Ghana",
  SA: "Saudi Arabia",
  AE: "United Arab Emirates",
  QA: "Qatar",
  OM: "Oman",
  KW: "Kuwait",
  TR: "Turkey",
  GR: "Greece",
  PT: "Portugal",
  PL: "Poland",
  UA: "Ukraine",
  BY: "Belarus",
  HU: "Hungary",
  CZ: "Czech Republic",
  SK: "Slovakia",
  AT: "Austria",
  IE: "Ireland",
  FI: "Finland",
  DK: "Denmark",
  BE: "Belgium",
  LU: "Luxembourg",
  IS: "Iceland",
  GL: "Greenland",
  EE: "Estonia",
  LV: "Latvia",
  LT: "Lithuania",
  RO: "Romania",
  BG: "Bulgaria",
  RS: "Serbia",
  HR: "Croatia",
  SI: "Slovenia",
  BA: "Bosnia and Herzegovina",
  ME: "Montenegro",
  MK: "North Macedonia",
  AL: "Albania",
  XK: "Kosovo",
  MD: "Moldova",
  AM: "Armenia",
  AZ: "Azerbaijan",
  GE: "Georgia",
  KZ: "Kazakhstan",
  UZ: "Uzbekistan",
  TM: "Turkmenistan",
  KG: "Kyrgyzstan",
  TJ: "Tajikistan",
  AF: "Afghanistan",
  PK: "Pakistan",
  BD: "Bangladesh",
  LK: "Sri Lanka",
  NP: "Nepal",
  BT: "Bhutan",
  MV: "Maldives",
  IR: "Iran",
  IQ: "Iraq",
  SY: "Syria",
  LB: "Lebanon",
  JO: "Jordan",
  IL: "Israel",
  PS: "Palestine",
  YE: "Yemen",
  BH: "Bahrain",
  CY: "Cyprus",
  MT: "Malta",
  BN: "Brunei",
  TL: "Timor-Leste",
  FJ: "Fiji",
  PG: "Papua New Guinea",
  SB: "Solomon Islands",
  VU: "Vanuatu",
  WS: "Samoa",
  TO: "Tonga",
  TV: "Tuvalu",
  KI: "Kiribati",
  NR: "Nauru",
  MH: "Marshall Islands",
  PW: "Palau",
  FM: "Micronesia",
  CK: "Cook Islands",
  NU: "Niue",
  TK: "Tokelau",
  NF: "Norfolk Island",
  GI: "Gibraltar",
  AX: "Aland Islands",
  FO: "Faroe Islands",
  SJ: "Svalbard and Jan Mayen",
  JE: "Jersey",
  GG: "Guernsey",
  IM: "Isle of Man",
  BM: "Bermuda",
  KY: "Cayman Islands",
  TC: "Turks and Caicos Islands",
  VG: "British Virgin Islands",
  AI: "Anguilla",
  MS: "Montserrat",
  GP: "Guadeloupe",
  MQ: "Martinique",
  MF: "Saint Martin",
  BL: "Saint Barthelemy",
  PM: "Saint Pierre and Miquelon",
  SX: "Sint Maarten",
  AW: "Aruba",
  CW: "Curacao",
  BQ: "Bonaire, Sint Eustatius, and Saba",
  KN: "Saint Kitts and Nevis",
  AG: "Antigua and Barbuda",
  DM: "Dominica",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  BB: "Barbados",
  GD: "Grenada",
  TT: "Trinidad and Tobago",
  VI: "United States Virgin Islands",
  PR: "Puerto Rico",
  GTMO: "Guantanamo Bay",
}

export const countryDescription = {
  CN: {
    description: [
      "Equal employment opportunities for all, regardless of ethnicity, race, gender, or religious belief.",
      "Equal pay for equal work mandated by law.",
      "Constitution ensures equal rights for women in all aspects of life.",
      "Regulations in place to prevent gender discrimination in recruitment.",
      "Amended Women's Protection Law of 2022 provides additional safeguards against discrimination and harassment.",
    ],
    ranking: "104",
    links: [],
  },
  IN: {
    description: [
      "Constitution prohibits discrimination based on gender, race, caste, and sex.",
      "Policies for equal pay for equal work mandated by the State.",
      "Right to equality is a fundamental right for all citizens.",
      "Labour laws protect equality for women in employment.",
      "Equal Remuneration Act enforces payment of equal wages for equal work, with penalties for non-compliance.",
    ],
    ranking: "135",
    links: [
      "https://labour.gov.in/sites/default/files/equal_remuneration_act_1976_0.pdf",
    ],
  },
}

export const countryDropdown = [
  { value: "null", label: "All Countries" },
  { value: "IN", label: "India" },
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "GB", label: "United Kingdom" },
  { value: "AU", label: "Australia" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "JP", label: "Japan" },
  { value: "CN", label: "China" },
  { value: "BR", label: "Brazil" },
  { value: "RU", label: "Russia" },
  { value: "ZA", label: "South Africa" },
  { value: "MX", label: "Mexico" },
  { value: "AR", label: "Argentina" },
  { value: "ES", label: "Spain" },
  { value: "IT", label: "Italy" },
  { value: "NL", label: "Netherlands" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "CH", label: "Switzerland" },
  { value: "NZ", label: "New Zealand" },
  { value: "SG", label: "Singapore" },
  { value: "KR", label: "South Korea" },
  { value: "ID", label: "Indonesia" },
  { value: "MY", label: "Malaysia" },
  { value: "TH", label: "Thailand" },
  { value: "VN", label: "Vietnam" },
  { value: "PH", label: "Philippines" },
  { value: "EG", label: "Egypt" },
  { value: "NG", label: "Nigeria" },
  { value: "KE", label: "Kenya" },
  { value: "GH", label: "Ghana" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "QA", label: "Qatar" },
  { value: "OM", label: "Oman" },
  { value: "KW", label: "Kuwait" },
  { value: "TR", label: "Turkey" },
  { value: "GR", label: "Greece" },
  { value: "PT", label: "Portugal" },
  { value: "PL", label: "Poland" },
  { value: "UA", label: "Ukraine" },
  { value: "BY", label: "Belarus" },
  { value: "HU", label: "Hungary" },
  { value: "CZ", label: "Czech Republic" },
  { value: "SK", label: "Slovakia" },
  { value: "AT", label: "Austria" },
  { value: "IE", label: "Ireland" },
  { value: "FI", label: "Finland" },
  { value: "DK", label: "Denmark" },
  { value: "BE", label: "Belgium" },
  { value: "LU", label: "Luxembourg" },
  { value: "IS", label: "Iceland" },
  { value: "GL", label: "Greenland" },
  { value: "EE", label: "Estonia" },
  { value: "LV", label: "Latvia" },
  { value: "LT", label: "Lithuania" },
  { value: "RO", label: "Romania" },
  { value: "BG", label: "Bulgaria" },
  { value: "RS", label: "Serbia" },
  { value: "HR", label: "Croatia" },
  { value: "SI", label: "Slovenia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "ME", label: "Montenegro" },
  { value: "MK", label: "North Macedonia" },
  { value: "AL", label: "Albania" },
  { value: "XK", label: "Kosovo" },
  { value: "MD", label: "Moldova" },
  { value: "AM", label: "Armenia" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "GE", label: "Georgia" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "TM", label: "Turkmenistan" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "AF", label: "Afghanistan" },
  { value: "PK", label: "Pakistan" },
  { value: "BD", label: "Bangladesh" },
  { value: "LK", label: "Sri Lanka" },
  { value: "NP", label: "Nepal" },
  { value: "BT", label: "Bhutan" },
  { value: "MV", label: "Maldives" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "SY", label: "Syria" },
  { value: "LB", label: "Lebanon" },
  { value: "JO", label: "Jordan" },
  { value: "IL", label: "Israel" },
  { value: "PS", label: "Palestine" },
  { value: "YE", label: "Yemen" },
  { value: "BH", label: "Bahrain" },
  { value: "CY", label: "Cyprus" },
  { value: "MT", label: "Malta" },
  { value: "BN", label: "Brunei" },
  { value: "TL", label: "Timor-Leste" },
  { value: "FJ", label: "Fiji" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "SB", label: "Solomon Islands" },
  { value: "VU", label: "Vanuatu" },
  { value: "WS", label: "Samoa" },
  { value: "TO", label: "Tonga" },
  { value: "TV", label: "Tuvalu" },
  { value: "KI", label: "Kiribati" },
  { value: "NR", label: "Nauru" },
  { value: "MH", label: "Marshall Islands" },
  { value: "PW", label: "Palau" },
  { value: "FM", label: "Micronesia" },
  { value: "CK", label: "Cook Islands" },
  { value: "NU", label: "Niue" },
  { value: "TK", label: "Tokelau" },
  { value: "NF", label: "Norfolk Island" },
  { value: "GI", label: "Gibraltar" },
  { value: "AX", label: "Aland Islands" },
  { value: "FO", label: "Faroe Islands" },
  { value: "SJ", label: "Svalbard and Jan Mayen" },
  { value: "JE", label: "Jersey" },
  { value: "GG", label: "Guernsey" },
  { value: "IM", label: "Isle of Man" },
  { value: "BM", label: "Bermuda" },
  { value: "KY", label: "Cayman Islands" },
  { value: "TC", label: "Turks and Caicos Islands" },
  { value: "VG", label: "British Virgin Islands" },
  { value: "AI", label: "Anguilla" },
  { value: "MS", label: "Montserrat" },
  { value: "GP", label: "Guadeloupe" },
  { value: "MQ", label: "Martinique" },
  { value: "MF", label: "Saint Martin" },
  { value: "BL", label: "Saint Barthelemy" },
  { value: "PM", label: "Saint Pierre and Miquelon" },
  { value: "SX", label: "Sint Maarten" },
  { value: "AW", label: "Aruba" },
  { value: "CW", label: "Curacao" },
  { value: "BQ", label: "Bonaire, Sint Eustatius, and Saba" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "DM", label: "Dominica" },
  { value: "LC", label: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "BB", label: "Barbados" },
  { value: "GD", label: "Grenada" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "VI", label: "United States Virgin Islands" },
  { value: "PR", label: "Puerto Rico" },
  { value: "GTMO", label: "Guantanamo Bay" },
]

export const colorScale = ["#e9d8a6", "#bb3e03"]
